import j1 from "../../images/finalimage/17.webp";
import j2 from "../../images/finalimage/18.webp";
import j3 from "../../images/finalimage/3.webp";
import j4 from "../../images/finalimage/19.webp";
import j5 from "../../images/finalimage/20.webp";
import j6 from "../../images/finalimage/12.webp";
import j7 from "../../images/finalimage/21.webp";
import j8 from "../../images/finalimage/23.webp";
import j9 from "../../images/finalimage/24.webp";
import j10 from "../../images/finalimage/25.webp";
import j11 from "../../images/finalimage/26.webp";
import j12 from "../../images/finalimage/27.webp";
import j13 from "../../images/finalimage/28.webp";
import j14 from "../../images/finalimage/29.webp";
import j15 from "../../images/finalimage/30.webp";
import j16 from "../../images/finalimage/31.webp";
import j17 from "../../images/finalimage/32.webp";
import j18 from "../../images/finalimage/34.webp";
import j19 from "../../images/finalimage/35.webp";
import j20 from "../../images/finalimage/36.webp";
import j21 from "../../images/finalimage/37.webp";
import j22 from "../../images/finalimage/38.webp";
import j23 from "../../images/finalimage/39.webp";
import j24 from "../../images/finalimage/40.webp";
import j25 from "../../images/finalimage/41.webp";
import j26 from "../../images/finalimage/42.webp";
import j27 from "../../images/finalimage/43.webp";
import j28 from "../../images/finalimage/44.webp";
import j29 from "../../images/finalimage/45.webp";
import j30 from "../../images/finalimage/46.webp";
import j31 from "../../images/finalimage/47.webp";
import j32 from "../../images/finalimage/48.webp";

export const products = [
  {
    id: 1,
    name: "Men's Regular Jeans",
    price: 89.99,
    image: j1,
    gender: "men",
    fit: "regular",
    color: "blue",
    rating: 4.2,
    stock: 8,
    sizes: ["XS", "SM", "MD", "LG", "XL"],
    model: "MRB-101",
  },
  {
    id: 2,
    name: "Women's Regular Jeans",
    price: 74.99,
    image: j2,
    gender: "women",
    fit: "regular",
    color: "blue",
    rating: 3.8,
    stock: 11,
    sizes: ["SM", "MD", "LG"],
    model: "WRB-102",
  },
  {
    id: 3,
    name: "Women's Skinny Jeans",
    price: 99.99,
    image: j3,
    gender: "women",
    fit: "skinny",
    color: "black",
    rating: 4.6,
    stock: 9,
    sizes: ["XS", "SM", "MD"],
    model: "WSK-103",
  },
  {
    id: 4,
    name: "Women's Baggy Jeans",
    price: 64.99,
    image: j4,
    gender: "women",
    fit: "baggy",
    color: "blue",
    rating: 3.2,
    stock: 0,
    sizes: ["MD", "LG", "XL"],
    model: "WBB-104",
  },
  {
    id: 5,
    name: "Women's Baggy Jeans",
    price: 84.99,
    image: j5,
    gender: "women",
    fit: "baggy",
    color: "white",
    rating: 3.9,
    stock: 10,
    sizes: ["SM", "MD", "LG"],
    model: "WBW-105",
  },
  {
    id: 6,
    name: "Men's Baggy Jeans",
    price: 59.99,
    image: j6,
    gender: "men",
    fit: "baggy",
    color: "blue",
    rating: 2.7,
    stock: 7,
    sizes: ["XS", "SM", "MD", "LG"],
    model: "MBB-106",
  },
  {
    id: 7,
    name: "Women's Regular Jeans",
    price: 69.99,
    image: j7,
    gender: "women",
    fit: "regular",
    color: "black",
    rating: 3.4,
    stock: 12,
    sizes: ["SM", "MD", "LG", "XL"],
    model: "WRK-107",
  },
  {
    id: 8,
    name: "Men's Skinny Jeans",
    price: 94.99,
    image: j8,
    gender: "men",
    fit: "skinny",
    color: "black",
    rating: 4.1,
    stock: 8,
    sizes: ["SM", "MD", "LG"],
    model: "MSK-108",
  },
  {
    id: 9,
    name: "Men's Baggy Jeans",
    price: 54.99,
    image: j9,
    gender: "men",
    fit: "baggy",
    color: "blue",
    rating: 2.5,
    stock: 6,
    sizes: ["XS", "SM", "MD", "LG"],
    model: "MBB-109",
  },
  {
    id: 10,
    name: "Men's Skinny Jeans",
    price: 79.99,
    image: j10,
    gender: "men",
    fit: "skinny",
    color: "blue",
    rating: 3.7,
    stock: 9,
    sizes: ["SM", "MD", "LG", "XL"],
    model: "MSB-110",
  },
  {
    id: 11,
    name: "Men's Baggy Jeans",
    price: 104.99,
    image: j11,
    gender: "men",
    fit: "baggy",
    color: "blue",
    rating: 4.4,
    stock: 11,
    sizes: ["SM", "MD"],
    model: "MBB-111",
  },
  {
    id: 12,
    name: "Men's Regular Jeans",
    price: 67.99,
    image: j12,
    gender: "men",
    fit: "regular",
    color: "white",
    rating: 3.1,
    stock: 7,
    sizes: ["SM", "MD", "LG"],
    model: "MRW-112",
  },
  {
    id: 13,
    name: "Men's Skinny Jeans",
    price: 72.99,
    image: j13,
    gender: "men",
    fit: "skinny",
    color: "blue",
    rating: 3.5,
    stock: 10,
    sizes: ["SM", "MD", "LG", "XL"],
    model: "MSB-113",
  },
  {
    id: 14,
    name: "Men's Skinny Jeans",
    price: 86.99,
    image: j14,
    gender: "men",
    fit: "skinny",
    color: "black",
    rating: 3.9,
    stock: 6,
    sizes: ["XS", "SM", "MD", "LG"],
    model: "MSK-114",
  },
  {
    id: 15,
    name: "Women's Regular Jeans",
    price: 91.99,
    image: j15,
    gender: "women",
    fit: "regular",
    color: "blue",
    rating: 4.3,
    stock: 12,
    sizes: ["SM", "MD", "LG", "XL"],
    model: "WRB-115",
  },
  {
    id: 16,
    name: "Men's Skinny Jeans",
    price: 57.99,
    image: j16,
    gender: "men",
    fit: "skinny",
    color: "blue",
    rating: 2.8,
    stock: 2,
    sizes: ["XS", "SM", "MD", "LG", "XL"],
    model: "MSB-116",
  },
  {
    id: 17,
    name: "Men's Skinny Jeans",
    price: 62.99,
    image: j17,
    gender: "men",
    fit: "skinny",
    color: "blue",
    rating: 3.2,
    stock: 8,
    sizes: ["SM", "MD", "LG"],
    model: "MSB-117",
  },
  {
    id: 18,
    name: "Men's Skinny Jeans",
    price: 108.99,
    image: j18,
    gender: "men",
    fit: "skinny",
    color: "white",
    rating: 4.5,
    stock: 11,
    sizes: ["XS", "SM", "MD", "LG", "XL"],
    model: "MSW-118",
  },
  {
    id: 19,
    name: "Men's Regular Jeans",
    price: 76.99,
    image: j19,
    gender: "men",
    fit: "regular",
    color: "black",
    rating: 3.6,
    stock: 6,
    sizes: ["SM", "MD"],
    model: "MRK-119",
  },
  {
    id: 20,
    name: "Men's Skinny Jeans",
    price: 83.99,
    image: j20,
    gender: "men",
    fit: "skinny",
    color: "black",
    rating: 3.8,
    stock: 9,
    sizes: ["MD", "LG", "XL"],
    model: "MSK-120",
  },
  {
    id: 21,
    name: "Men's Regular Jeans",
    price: 97.99,
    image: j21,
    gender: "men",
    fit: "regular",
    color: "blue",
    rating: 4.0,
    stock: 12,
    sizes: ["XS", "SM", "MD", "LG"],
    model: "MRB-121",
  },
  {
    id: 22,
    name: "Women's Baggy Jeans",
    price: 44.99,
    image: j22,
    gender: "women",
    fit: "baggy",
    color: "blue",
    rating: 2.2,
    stock: 7,
    sizes: ["SM", "MD", "LG", "XL"],
    model: "WBB-122",
  },
  {
    id: 23,
    name: "Women's Baggy Jeans",
    price: 38.99,
    image: j23,
    gender: "women",
    fit: "baggy",
    color: "blue",
    rating: 2.4,
    stock: 13,
    sizes: ["XS", "SM", "MD", "LG", "XL"],
    model: "WBB-123",
  },
  {
    id: 24,
    name: "Men's Regular Jeans",
    price: 114.99,
    image: j24,
    gender: "men",
    fit: "regular",
    color: "black",
    rating: 4.2,
    stock: 8,
    sizes: ["XS", "SM", "MD", "LG", "XL"],
    model: "MRK-124",
  },
  {
    id: 25,
    name: "Women's Regular Jeans",
    price: 119.99,
    image: j25,
    gender: "women",
    fit: "regular",
    color: "blue",
    rating: 4.5,
    stock: 11,
    sizes: ["SM", "MD", "LG", "XL"],
    model: "WRB-125",
  },
  {
    id: 26,
    name: "Women's Skinny Jeans",
    price: 126.99,
    image: j26,
    gender: "women",
    fit: "skinny",
    color: "blue",
    rating: 3.7,
    stock: 6,
    sizes: ["XS", "SM", "MD", "LG"],
    model: "WSB-126",
  },
  {
    id: 27,
    name: "Women's Regular Jeans",
    price: 132.99,
    image: j27,
    gender: "women",
    fit: "regular",
    color: "blue",
    rating: 4.7,
    stock: 9,
    sizes: ["SM", "MD", "LG"],
    model: "WRB-127",
  },
  {
    id: 28,
    name: "Women's Baggy Jeans",
    price: 138.99,
    image: j28,
    gender: "women",
    fit: "baggy",
    color: "blue",
    rating: 3.9,
    stock: 12,
    sizes: ["SM", "MD", "LG", "XL"],
    model: "WBB-128",
  },
  {
    id: 29,
    name: "Women's Baggy Jeans",
    price: 142.99,
    image: j29,
    gender: "women",
    fit: "baggy",
    color: "blue",
    rating: 4.9,
    stock: 7,
    sizes: ["XS", "SM", "MD", "LG"],
    model: "WBB-129",
  },
  {
    id: 30,
    name: "Men's Regular Jeans",
    price: 147.99,
    image: j30,
    gender: "men",
    fit: "regular",
    color: "black",
    rating: 3.8,
    stock: 10,
    sizes: ["XS", "SM", "MD", "LG", "XL"],
    model: "MRK-130",
  },
  {
    id: 31,
    name: "Men's Baggy Jeans",
    price: 124.99,
    image: j31,
    gender: "men",
    fit: "baggy",
    color: "blue",
    rating: 3.6,
    stock: 4,
    sizes: ["SM", "MD", "LG", "XL"],
    model: "MBB-131",
  },
  {
    id: 32,
    name: "Men's Regular Jeans",
    price: 116.99,
    image: j32,
    gender: "men",
    fit: "regular",
    color: "blue",
    rating: 4.4,
    stock: 8,
    sizes: ["XS", "SM", "MD", "LG"],
    model: "MRB-132",
  },
];
